{{- if and (not .Values.signatures.existingSecret) (or .Values.signatures.sources .Values.signatures.dbUrl) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "exav-chart.secretName" . }}
  labels:
    {{- include "exav-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.signatures.sources }}
  sig-sources: {{ join "," .Values.signatures.sources | quote }}
  {{- end }}
  {{- if .Values.signatures.dbUrl }}
  db-url: {{ .Values.signatures.dbUrl | quote }}
  {{- end }}
{{- end }}
